index = ['host_is_superhost', 'host_listings_count', 'latitude', 'longitude','accommodates', 'bathrooms', 'bedrooms', 'beds', 'amenities','extra_people', 'minimum_nights', 'instant_bookable', 'year', 'month','property_type_Apartment', 'property_type_Bed and breakfast','property_type_Condominium', 'property_type_Guest suite','property_type_Guesthouse', 'property_type_Hostel', 'property_type_House', 'property_type_Loft', 'property_type_Other','property_type_Serviced apartment', 'cancellation_policy_flexible',
'cancellation_policy_moderate', 'cancellation_policy_strict','cancellation_policy_strict_14_with_grace_period','room_type_Entire home/apt', 'room_type_Hotel room','room_type_Private room', 'room_type_Shared room']
new_index = ['host_is_superhost', 'host_listings_count', 'latitude', 'longitude','accommodates', 'bathrooms', 'bedrooms', 'beds', 'amenities','extra_people', 'minimum_nights', 'instant_bookable', 'year', 'month','property_type_Apartment', 'property_type_Bed_and_breakfast','property_type_Condominium', 'property_type_Guest_suite','property_type_Guesthouse', 'property_type_Hostel', 'property_type_House', 'property_type_Loft', 'property_type_Other','property_type_Serviced_apartment', 'cancellation_policy_flexible',
'cancellation_policy_moderate', 'cancellation_policy_strict','cancellation_policy_strict_14_with_grace_period','room_type_Entire_home_apt', 'room_type_Hotel_room','room_type_Private_room', 'room_type_Shared_room']
ddd = {
        "property_type_Bed and breakfast": 0,
        "property_type_Apartment": 1,
        "property_type_Condominium": 0,
        "property_type_Guest suite": 0,
        "property_type_Guesthouse": 0,
        "property_type_Hostel": 0,
        "property_type_House": 0,
        "property_type_Loft": 0,
        "property_type_Other": 0,
        "property_type_Serviced apartment": 0,
        "room_type_Entire home/apt": 1,
        "room_type_Hotel room": 0,
        "room_type_Private room": 0,
        "room_type_Shared room": 0,
        "cancellation_policy_flexible": 1,
        "cancellation_policy_moderate": 0,
        "cancellation_policy_strict": 0,
        "cancellation_policy_strict_14_with_grace_period": 0,
        "latitude": -22.998264,
        "longitude": -43.41536,
        "accommodates": 6,
        "bathrooms": 2,
        "bedrooms": 2,
        "beds": 3,
        "extra_people": 0.0,
        "minimum_nights": 1,
        "year": 2018,
        "month": 10,
        "amenities": 16,
        "host_listings_count": 1,
        "host_is_superhost": 0,
        "instant_bookable": 0,
    }
dddxxx = {
        "property_type_Bed and breakfast": 0,
        "property_type_Apartment": 1,
        "property_type_Condominium": 0,
        "property_type_Guest suite": 0,
        "property_type_Guesthouse": 0,
        "property_type_Hostel": 0,
        "property_type_House": 0,
        "property_type_Loft": 0,
        "property_type_Other": 0,
        "property_type_Serviced apartment": 0,
        "room_type_Entire home/apt": 1,
        "room_type_Hotel room": 0,
        "room_type_Private room": 0,
        "room_type_Shared room": 0,
        "cancellation_policy_flexible": 1,
        "cancellation_policy_moderate": 0,
        "cancellation_policy_strict": 0,
        "cancellation_policy_strict_14_with_grace_period": 0,
        "latitude": 0,
        "longitude": 0,
        "accommodates": 0,
        "bathrooms": 0,
        "bedrooms": 0,
        "beds": 0,
        "extra_people": 0.0,
        "minimum_nights":0,
        "year": 0,
        "month": 0,
        "amenities": 0,
        "host_listings_count": 0,
        "host_is_superhost": 1,
        "instant_bookable": 1,
    }